export const drugs = [
    { name: 'Aspirin', brand: 'Bayer', generic: 'Aspirin', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Used to reduce fever, pain, and inflammation.' },
    { name: 'Ibuprofen', brand: 'Advil', generic: 'Ibuprofen', dosageForm: 'Tablet', strength: '200mg', route: 'Oral', description: 'Nonsteroidal anti-inflammatory drug (NSAID).' },
    { name: 'Paracetamol', brand: 'Tylenol', generic: 'Paracetamol', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Pain reliever and fever reducer.' },
    { name: 'Amoxicillin', brand: 'Amoxil', generic: 'Amoxicillin', dosageForm: 'Capsule', strength: '250mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { name: 'Metformin', brand: 'Glucophage', generic: 'Metformin', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Used to treat type 2 diabetes.' },
    { name: 'Lisinopril', brand: 'Zestril', generic: 'Lisinopril', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to treat high blood pressure.' },
    { name: 'Atorvastatin', brand: 'Lipitor', generic: 'Atorvastatin', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to lower cholesterol levels.' },
    { name: 'Amlodipine', brand: 'Norvasc', generic: 'Amlodipine', dosageForm: 'Tablet', strength: '5mg', route: 'Oral', description: 'Used to treat high blood pressure and angina.' },
    { name: 'Simvastatin', brand: 'Zocor', generic: 'Simvastatin', dosageForm: 'Tablet', strength: '20mg', route: 'Oral', description: 'Used to lower cholesterol levels.' },
    { name: 'Losartan', brand: 'Cozaar', generic: 'Losartan', dosageForm: 'Tablet', strength: '50mg', route: 'Oral', description: 'Used to treat high blood pressure.' },
    { name: 'Clopidogrel', brand: 'Plavix', generic: 'Clopidogrel', dosageForm: 'Tablet', strength: '75mg', route: 'Oral', description: 'Used to prevent blood clots.' },
    { name: 'Albuterol', brand: 'ProAir', generic: 'Albuterol', dosageForm: 'Inhaler', strength: '90mcg', route: 'Inhalation', description: 'Used to treat asthma and COPD.' },
    { name: 'Metoprolol', brand: 'Lopressor', generic: 'Metoprolol', dosageForm: 'Tablet', strength: '50mg', route: 'Oral', description: 'Used to treat high blood pressure and angina.' },
    { name: 'Omeprazole', brand: 'Prilosec', generic: 'Omeprazole', dosageForm: 'Capsule', strength: '20mg', route: 'Oral', description: 'Used to treat acid reflux and GERD.' },
    { name: 'Furosemide', brand: 'Lasix', generic: 'Furosemide', dosageForm: 'Tablet', strength: '40mg', route: 'Oral', description: 'Used to treat fluid retention and high blood pressure.' },
    { name: 'Gabapentin', brand: 'Neurontin', generic: 'Gabapentin', dosageForm: 'Capsule', strength: '300mg', route: 'Oral', description: 'Used to treat seizures and nerve pain.' },
    { name: 'Hydrochlorothiazide', brand: 'Microzide', generic: 'Hydrochlorothiazide', dosageForm: 'Tablet', strength: '25mg', route: 'Oral', description: 'Used to treat high blood pressure and fluid retention.' },
    { name: 'Sertraline', brand: 'Zoloft', generic: 'Sertraline', dosageForm: 'Tablet', strength: '50mg', route: 'Oral', description: 'Used to treat depression and anxiety.' },
    { name: 'Zolpidem', brand: 'Ambien', generic: 'Zolpidem', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to treat insomnia.' },
    { name: 'Citalopram', brand: 'Celexa', generic: 'Citalopram', dosageForm: 'Tablet', strength: '20mg', route: 'Oral', description: 'Used to treat depression.' },
    { name: 'Tramadol', brand: 'Ultram', generic: 'Tramadol', dosageForm: 'Tablet', strength: '50mg', route: 'Oral', description: 'Used to treat moderate to severe pain.' },
    { name: 'Pantoprazole', brand: 'Protonix', generic: 'Pantoprazole', dosageForm: 'Tablet', strength: '40mg', route: 'Oral', description: 'Used to treat acid reflux and GERD.' },
    { name: 'Duloxetine', brand: 'Cymbalta', generic: 'Duloxetine', dosageForm: 'Capsule', strength: '30mg', route: 'Oral', description: 'Used to treat depression, anxiety, and chronic pain.' },
    { name: 'Trazodone', brand: 'Desyrel', generic: 'Trazodone', dosageForm: 'Tablet', strength: '100mg', route: 'Oral', description: 'Used to treat depression and insomnia.' },
    { name: 'Carvedilol', brand: 'Coreg', generic: 'Carvedilol', dosageForm: 'Tablet', strength: '12.5mg', route: 'Oral', description: 'Used to treat high blood pressure and heart failure.' },
    { name: 'Cyclobenzaprine', brand: 'Flexeril', generic: 'Cyclobenzaprine', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to treat muscle spasms.' },
    { name: 'Meloxicam', brand: 'Mobic', generic: 'Meloxicam', dosageForm: 'Tablet', strength: '15mg', route: 'Oral', description: 'Used to treat pain and inflammation.' },
    { name: 'Tamsulosin', brand: 'Flomax', generic: 'Tamsulosin', dosageForm: 'Capsule', strength: '0.4mg', route: 'Oral', description: 'Used to treat enlarged prostate (BPH).' },
    { name: 'Allopurinol', brand: 'Zyloprim', generic: 'Allopurinol', dosageForm: 'Tablet', strength: '300mg', route: 'Oral', description: 'Used to treat gout and kidney stones.' },
    { name: 'Clonazepam', brand: 'Klonopin', generic: 'Clonazepam', dosageForm: 'Tablet', strength: '1mg', route: 'Oral', description: 'Used to treat seizures and panic disorders.' },
    { name: 'Warfarin', brand: 'Coumadin', generic: 'Warfarin', dosageForm: 'Tablet', strength: '5mg', route: 'Oral', description: 'Used to prevent blood clots.' },
    { name: 'Amitriptyline', brand: 'Elavil', generic: 'Amitriptyline', dosageForm: 'Tablet', strength: '25mg', route: 'Oral', description: 'Used to treat depression and nerve pain.' },
    { name: 'Diclofenac', brand: 'Voltaren', generic: 'Diclofenac', dosageForm: 'Tablet', strength: '50mg', route: 'Oral', description: 'Used to treat pain and inflammation.' },
    { name: 'Insulin Glargine', brand: 'Lantus', generic: 'Insulin Glargine', dosageForm: 'Injection', strength: '100 units/mL', route: 'Subcutaneous', description: 'Used to treat diabetes.' },
    { name: 'Venlafaxine', brand: 'Effexor', generic: 'Venlafaxine', dosageForm: 'Tablet', strength: '75mg', route: 'Oral', description: 'Used to treat depression and anxiety.' },
    { name: 'Ranitidine', brand: 'Zantac', generic: 'Ranitidine', dosageForm: 'Tablet', strength: '150mg', route: 'Oral', description: 'Used to treat acid reflux and ulcers.' },
    { name: 'Azithromycin', brand: 'Zithromax', generic: 'Azithromycin', dosageForm: 'Tablet', strength: '250mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { name: 'Doxycycline', brand: 'Vibramycin', generic: 'Doxycycline', dosageForm: 'Tablet', strength: '100mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { name: 'Oxycodone', brand: 'OxyContin', generic: 'Oxycodone', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to treat moderate to severe pain.' },
    { name: 'Morphine', brand: 'MS Contin', generic: 'Morphine', dosageForm: 'Tablet', strength: '30mg', route: 'Oral', description: 'Used to treat severe pain.' },
    { name: 'Metronidazole', brand: 'Flagyl', generic: 'Metronidazole', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Antibiotic used to treat bacterial and protozoal infections.' },
    { name: 'Prednisone', brand: 'Deltasone', generic: 'Prednisone', dosageForm: 'Tablet', strength: '20mg', route: 'Oral', description: 'Corticosteroid used to treat inflammation.' },
    { name: 'Lorazepam', brand: 'Ativan', generic: 'Lorazepam', dosageForm: 'Tablet', strength: '1mg', route: 'Oral', description: 'Used to treat anxiety disorders.' },
    { name: 'Hydrocodone/Acetaminophen', brand: 'Vicodin', generic: 'Hydrocodone/Acetaminophen', dosageForm: 'Tablet', strength: '5mg/325mg', route: 'Oral', description: 'Used to treat moderate to severe pain.' },
    { name: 'Levothyroxine', brand: 'Synthroid', generic: 'Levothyroxine', dosageForm: 'Tablet', strength: '100mcg', route: 'Oral', description: 'Used to treat hypothyroidism.' },
    { name: 'Carbamazepine', brand: 'Tegretol', generic: 'Carbamazepine', dosageForm: 'Tablet', strength: '200mg', route: 'Oral', description: 'Used to treat seizures and nerve pain.' },
    { name: 'Clindamycin', brand: 'Cleocin', generic: 'Clindamycin', dosageForm: 'Capsule', strength: '300mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { name: 'Loratadine', brand: 'Claritin', generic: 'Loratadine', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to treat allergy symptoms.' },
    { name: 'Propranolol', brand: 'Inderal', generic: 'Propranolol', dosageForm: 'Tablet', strength: '40mg', route: 'Oral', description: 'Used to treat high blood pressure and anxiety.' },
    { name: 'Fluconazole', brand: 'Diflucan', generic: 'Fluconazole', dosageForm: 'Tablet', strength: '150mg', route: 'Oral', description: 'Antifungal used to treat fungal infections.' },
];