export const drugs = [
    { id: 'AS01', name: 'Aspirin', brand: 'Bayer', generic: 'Aspirin', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Used to reduce fever, pain, and inflammation.' },
    { id: 'IB02', name: 'Ibuprofen', brand: 'Advil', generic: 'Ibuprofen', dosageForm: 'Tablet', strength: '200mg', route: 'Oral', description: 'Nonsteroidal anti-inflammatory drug (NSAID).' },
    { id: 'AM03', name: 'Amoxicillin', brand: 'Amoxil', generic: 'Amoxicillin', dosageForm: 'Capsule', strength: '500mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { id: 'PA04', name: 'Paracetamol', brand: 'Tylenol', generic: 'Paracetamol', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Used to treat pain and fever.' },
    { id: 'ME05', name: 'Metformin', brand: 'Glucophage', generic: 'Metformin', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Used to treat type 2 diabetes.' },
    { id: 'LI06', name: 'Lisinopril', brand: 'Prinivil', generic: 'Lisinopril', dosageForm: 'Tablet', strength: '20mg', route: 'Oral', description: 'Used to treat high blood pressure and heart failure.' },
    { id: 'AT07', name: 'Atorvastatin', brand: 'Lipitor', generic: 'Atorvastatin', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to lower cholesterol.' },
    { id: 'AL08', name: 'Alprazolam', brand: 'Xanax', generic: 'Alprazolam', dosageForm: 'Tablet', strength: '0.5mg', route: 'Oral', description: 'Used to treat anxiety and panic disorders.' },
    { id: 'OM09', name: 'Omeprazole', brand: 'Prilosec', generic: 'Omeprazole', dosageForm: 'Capsule', strength: '20mg', route: 'Oral', description: 'Used to treat gastroesophageal reflux disease (GERD).' },
    { id: 'AM10', name: 'Amlodipine', brand: 'Norvasc', generic: 'Amlodipine', dosageForm: 'Tablet', strength: '5mg', route: 'Oral', description: 'Used to treat high blood pressure and chest pain.' },
    { id: 'CI11', name: 'Ciprofloxacin', brand: 'Cipro', generic: 'Ciprofloxacin', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Antibiotic used to treat various infections.' },
    { id: 'FL12', name: 'Fluoxetine', brand: 'Prozac', generic: 'Fluoxetine', dosageForm: 'Capsule', strength: '20mg', route: 'Oral', description: 'Used to treat depression, OCD, and panic disorder.' },
    { id: 'TE13', name: 'Tetracycline', brand: 'Sumycin', generic: 'Tetracycline', dosageForm: 'Capsule', strength: '500mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { id: 'ME14', name: 'Methotrexate', brand: 'Trexall', generic: 'Methotrexate', dosageForm: 'Tablet', strength: '2.5mg', route: 'Oral', description: 'Used to treat certain types of cancer and autoimmune diseases.' },
    { id: 'GL15', name: 'Glipizide', brand: 'Glucotrol', generic: 'Glipizide', dosageForm: 'Tablet', strength: '5mg', route: 'Oral', description: 'Used to treat type 2 diabetes.' },
    { id: 'FA16', name: 'Furosemide', brand: 'Lasix', generic: 'Furosemide', dosageForm: 'Tablet', strength: '40mg', route: 'Oral', description: 'Used to treat fluid retention and swelling.' },
    { id: 'TR17', name: 'Tramadol', brand: 'Ultram', generic: 'Tramadol', dosageForm: 'Tablet', strength: '50mg', route: 'Oral', description: 'Used to treat moderate to severe pain.' },
    { id: 'CO18', name: 'Corticosteroid', brand: 'Deltasone', generic: 'Prednisone', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to treat inflammatory conditions.' },
    { id: 'CE19', name: 'Cetirizine', brand: 'Zyrtec', generic: 'Cetirizine', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to treat allergy symptoms.' },
    { id: 'AZ20', name: 'Azithromycin', brand: 'Zithromax', generic: 'Azithromycin', dosageForm: 'Tablet', strength: '250mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { id: 'SY21', name: 'Synthroid', brand: 'Synthroid', generic: 'Levothyroxine', dosageForm: 'Tablet', strength: '50mcg', route: 'Oral', description: 'Used to treat hypothyroidism.' },
    { id: 'FL22', name: 'Flonase', brand: 'Flonase', generic: 'Fluticasone', dosageForm: 'Nasal Spray', strength: '50mcg', route: 'Nasal', description: 'Used to treat nasal congestion and allergies.' },
    { id: 'NE23', name: 'Neomycin', brand: 'Mycifradin', generic: 'Neomycin', dosageForm: 'Ointment', strength: '0.5%', route: 'Topical', description: 'Used to treat bacterial skin infections.' },
    { id: 'SU24', name: 'Sulfasalazine', brand: 'Azulfidine', generic: 'Sulfasalazine', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Used to treat ulcerative colitis and rheumatoid arthritis.' },
    { id: 'HY25', name: 'Hydrochlorothiazide', brand: 'Microzide', generic: 'Hydrochlorothiazide', dosageForm: 'Tablet', strength: '25mg', route: 'Oral', description: 'Used to treat high blood pressure.' },
    { id: 'DI26', name: 'Diazepam', brand: 'Valium', generic: 'Diazepam', dosageForm: 'Tablet', strength: '5mg', route: 'Oral', description: 'Used to treat anxiety, muscle spasms, and seizures.' },
    { id: 'CA27', name: 'Captopril', brand: 'Capoten', generic: 'Captopril', dosageForm: 'Tablet', strength: '25mg', route: 'Oral', description: 'Used to treat high blood pressure and heart failure.' },
    { id: 'PR28', name: 'Prednisolone', brand: 'Orapred', generic: 'Prednisolone', dosageForm: 'Tablet', strength: '5mg', route: 'Oral', description: 'Used to treat various inflammatory and autoimmune conditions.' },
    { id: 'VI29', name: 'Vitamin D', brand: 'Drisdol', generic: 'Ergocalciferol', dosageForm: 'Capsule', strength: '50,000 IU', route: 'Oral', description: 'Used to treat vitamin D deficiency.' },
    { id: 'AL30', name: 'Allopurinol', brand: 'Zyloprim', generic: 'Allopurinol', dosageForm: 'Tablet', strength: '300mg', route: 'Oral', description: 'Used to treat gout and kidney stones.' },
    { id: 'DO31', name: 'Doxycycline', brand: 'Vibramycin', generic: 'Doxycycline', dosageForm: 'Capsule', strength: '100mg', route: 'Oral', description: 'Antibiotic used to treat various infections.' },
    { id: 'CE32', name: 'Cephalexin', brand: 'Keflex', generic: 'Cephalexin', dosageForm: 'Capsule', strength: '500mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { id: 'CL33', name: 'Clindamycin', brand: 'Cleocin', generic: 'Clindamycin', dosageForm: 'Capsule', strength: '300mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { id: 'DO34', name: 'Donepezil', brand: 'Aricept', generic: 'Donepezil', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to treat dementia related to Alzheimer\'s disease.' },
    { id: 'ME35', name: 'Methylprednisolone', brand: 'Medrol', generic: 'Methylprednisolone', dosageForm: 'Tablet', strength: '4mg', route: 'Oral', description: 'Used to treat inflammatory conditions.' },
    { id: 'AM36', name: 'Amitriptyline', brand: 'Elavil', generic: 'Amitriptyline', dosageForm: 'Tablet', strength: '25mg', route: 'Oral', description: 'Used to treat depression and neuropathic pain.' },
    { id: 'ES37', name: 'Esomeprazole', brand: 'Nexium', generic: 'Esomeprazole', dosageForm: 'Capsule', strength: '40mg', route: 'Oral', description: 'Used to treat GERD and other stomach acid-related conditions.' },
    { id: 'CL38', name: 'Clopidogrel', brand: 'Plavix', generic: 'Clopidogrel', dosageForm: 'Tablet', strength: '75mg', route: 'Oral', description: 'Used to prevent blood clots in patients with heart disease.' },
    { id: 'LO39', name: 'Losartan', brand: 'Cozaar', generic: 'Losartan', dosageForm: 'Tablet', strength: '50mg', route: 'Oral', description: 'Used to treat high blood pressure.' },
    { id: 'FA40', name: 'Famotidine', brand: 'Pepcid', generic: 'Famotidine', dosageForm: 'Tablet', strength: '20mg', route: 'Oral', description: 'Used to treat stomach ulcers and GERD.' },
    { id: 'ME41', name: 'Methocarbamol', brand: 'Robaxin', generic: 'Methocarbamol', dosageForm: 'Tablet', strength: '500mg', route: 'Oral', description: 'Muscle relaxant used to treat muscle pain and spasms.' },
    { id: 'RI42', name: 'Risperidone', brand: 'Risperdal', generic: 'Risperidone', dosageForm: 'Tablet', strength: '2mg', route: 'Oral', description: 'Used to treat schizophrenia and bipolar disorder.' },
    { id: 'LA43', name: 'Lactulose', brand: 'Enulose', generic: 'Lactulose', dosageForm: 'Solution', strength: '10g/15mL', route: 'Oral', description: 'Used to treat constipation.' },
    { id: 'SP44', name: 'Spironolactone', brand: 'Aldactone', generic: 'Spironolactone', dosageForm: 'Tablet', strength: '25mg', route: 'Oral', description: 'Used to treat fluid retention, high blood pressure, and hyperaldosteronism.' },
    { id: 'SU45', name: 'Sulfamethoxazole', brand: 'Bactrim', generic: 'Sulfamethoxazole', dosageForm: 'Tablet', strength: '800mg', route: 'Oral', description: 'Antibiotic used to treat bacterial infections.' },
    { id: 'DO46', name: 'Docusate', brand: 'Colace', generic: 'Docusate', dosageForm: 'Capsule', strength: '100mg', route: 'Oral', description: 'Stool softener used to treat constipation.' },
    { id: 'ME47', name: 'Meloxicam', brand: 'Mobic', generic: 'Meloxicam', dosageForm: 'Tablet', strength: '15mg', route: 'Oral', description: 'Used to treat osteoarthritis and rheumatoid arthritis.' },
    { id: 'PH48', name: 'Phenytoin', brand: 'Dilantin', generic: 'Phenytoin', dosageForm: 'Capsule', strength: '100mg', route: 'Oral', description: 'Anticonvulsant used to prevent seizures.' },
    { id: 'AL49', name: 'Albuterol', brand: 'ProAir', generic: 'Albuterol', dosageForm: 'Inhaler', strength: '90mcg', route: 'Inhalation', description: 'Used to treat asthma and other breathing disorders.' },
    { id: 'MO50', name: 'Montelukast', brand: 'Singulair', generic: 'Montelukast', dosageForm: 'Tablet', strength: '10mg', route: 'Oral', description: 'Used to prevent asthma attacks and treat allergies.' }
];
